# Generated by Django 2.2.6 on 2019-12-02 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CLICKER', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='public',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectToSavedStates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLICKER.Project')),
                ('savedState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLICKER.SavedState')),
            ],
        ),
    ]
