# Generated by Django 2.2.6 on 2019-11-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLICKER', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedstate',
            name='autosaved',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
