# Generated by Django 3.1 on 2020-09-12 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CLICKER', '0002_auto_20200911_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectToMostRecentState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CLICKER.project')),
                ('saved_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CLICKER.savedstate')),
            ],
        ),
    ]
