# Generated by Django 3.1.1 on 2020-09-19 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CLICKER', '0003_projecttomostrecentstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttomostrecentstate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLICKER.project'),
        ),
        migrations.AlterField(
            model_name='projecttomostrecentstate',
            name='saved_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CLICKER.savedstate'),
        ),
    ]
